#!/usr/bin/env node
/**
 * create-pdf.js
 * Generates a landscape PDF with a cover page and one screenshot per page.
 *
 * Usage: node create-pdf.js
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const APPS = [
  { dir: '01-lbts', name: 'LBTS', tagline: 'Legislative Bill Tracker' },
  { dir: '02-mvrx', name: 'MVRX', tagline: 'Member Voting Record Explorer' },
  { dir: '03-cmap', name: 'CMAP', tagline: 'Committee Meeting & Agenda Planner' },
  { dir: '04-sclx', name: 'SCLX', tagline: 'SC Legal Code Cross-Reference Engine' },
  { dir: '05-bfis', name: 'BFIS', tagline: 'Budget & Fiscal Impact Synthesizer' },
  { dir: '06-dmap', name: 'DMAP', tagline: 'District & Delegation Mapper' },
  { dir: '07-spnx', name: 'SPNX', tagline: 'Sponsor Network & Collaboration Graph' },
  { dir: '08-amdt', name: 'AMDT', tagline: 'Amendment Tracker & Impact Analyzer' },
  { dir: '09-lsiv', name: 'LSIV', tagline: 'Legislative Session Intelligence View' },
  { dir: '10-prfn', name: 'PRFN', tagline: 'Public Research & Find Navigator' },
  { dir: '11-bcal', name: 'BCAL', tagline: 'Bill Activity Calendar & Legislative Pulse' },
  { dir: '12-cwhp', name: 'CWHP', tagline: 'Committee Workload & Health Profile' },
  { dir: '13-jtfr', name: 'JTFR', tagline: 'Journal & Transcript Research Finder' },
  { dir: '14-rcvz', name: 'RCVZ', tagline: 'Roll Call Vote Analyzer & Visualization' },
  { dir: '15-mtxs', name: 'MTXS', tagline: 'Member Tenure & Experience Scorecard' },
  { dir: '16-lcdb', name: 'LCDB', tagline: 'Legislative Comparison Dashboard' },
  { dir: '17-pgov', name: 'PGOV', tagline: 'Party Governance & Caucus Analyzer' },
  { dir: '18-whip', name: 'WHIP', tagline: 'Whip Count & Vote Prediction Simulator' },
  { dir: '19-actx', name: 'ACTX', tagline: 'Action Timeline & Cross-Chamber Tracker' },
  { dir: '20-rldr', name: 'RLDR', tagline: 'Rules & Leadership Directory' },
];

const PROJECT_ROOT = __dirname;
const SCREENSHOTS_DIR = path.join(PROJECT_ROOT, 'screenshots');
const OUTPUT_PDF = path.join(PROJECT_ROOT, 'Ideas_Engine_Concepts.pdf');

const NAVY = '#003466';
const GOLD = '#C09D3B';
const WHITE = '#FFFFFF';
const GRAY = '#666666';

// Helper: draw text at exact position, no auto-pagination
function drawText(doc, text, x, y, opts) {
  doc.text(text, x, y, Object.assign({ lineBreak: false }, opts));
}

function createPDF() {
  // Use huge bottom margin to prevent pdfkit from ever auto-adding pages
  const doc = new PDFDocument({
    layout: 'landscape',
    size: 'letter',
    margins: { top: 0, bottom: 0, left: 0, right: 0 },
    autoFirstPage: false,
    bufferPages: true,
    info: {
      Title: 'SC General Assembly - Ideas Engine Concepts',
      Author: 'Legislative Services Agency - IT Department',
      Subject: 'Legislative App Concepts Generated by Claude AI',
      Creator: 'Claude Code',
    },
  });

  const stream = fs.createWriteStream(OUTPUT_PDF);
  doc.pipe(stream);

  // Letter landscape: 792 x 612
  const W = 792;
  const H = 612;

  // =========================================================================
  // COVER PAGE
  // =========================================================================
  doc.addPage({ layout: 'landscape', size: 'letter', margins: { top: 0, bottom: 0, left: 0, right: 0 } });

  // Navy background
  doc.rect(0, 0, W, H).fill(NAVY);
  // Gold accent top
  doc.rect(0, 0, W, 6).fill(GOLD);

  const cx = W / 2;

  doc.font('Helvetica-Bold').fontSize(38).fillColor(WHITE);
  drawText(doc, 'Ideas Engine', 0, 140, { align: 'center', width: W });

  doc.font('Helvetica').fontSize(16).fillColor(GOLD);
  drawText(doc, 'SC General Assembly', 0, 192, { align: 'center', width: W });

  // Divider
  doc.moveTo(cx - 120, 230).lineTo(cx + 120, 230).lineWidth(2).strokeColor(GOLD).stroke();

  // Description
  doc.font('Helvetica').fontSize(13).fillColor(WHITE);
  drawText(doc, 'A collection of 20 legislative app concepts created by Claude AI,', 0, 252, { align: 'center', width: W });
  drawText(doc, 'exploring creative applications of the SC Statehouse REST API endpoints.', 0, 272, { align: 'center', width: W });

  // Stats
  doc.font('Helvetica-Bold').fontSize(28).fillColor(GOLD);
  drawText(doc, '20', cx - 180, 320, { width: 120, align: 'center' });
  drawText(doc, '50+', cx - 60, 320, { width: 120, align: 'center' });
  drawText(doc, '6', cx + 60, 320, { width: 120, align: 'center' });

  doc.font('Helvetica').fontSize(10).fillColor(WHITE);
  drawText(doc, 'App Concepts', cx - 180, 354, { width: 120, align: 'center' });
  drawText(doc, 'API Endpoints', cx - 60, 354, { width: 120, align: 'center' });
  drawText(doc, 'Target Audiences', cx + 60, 354, { width: 120, align: 'center' });

  // Series
  doc.font('Helvetica-Bold').fontSize(11).fillColor(GOLD);
  drawText(doc, 'SERIES 1 (01\u201310)', cx - 200, 400, { width: 180, align: 'center' });
  drawText(doc, 'SERIES 2 (11\u201320)', cx + 20, 400, { width: 180, align: 'center' });

  doc.font('Helvetica').fontSize(9.5).fillColor(WHITE);
  drawText(doc, 'Dark theme \u2022 Navy & Gold', cx - 200, 418, { width: 180, align: 'center' });
  drawText(doc, 'LSA branded \u2022 Official Style Guide', cx + 20, 418, { width: 180, align: 'center' });

  // Footer
  doc.font('Helvetica').fontSize(9).fillColor(GRAY);
  drawText(doc, 'Legislative Services Agency \u2022 IT Department \u2022 South Carolina General Assembly', 0, H - 70, { align: 'center', width: W });
  drawText(doc, 'Powered by the SC Statehouse REST API (rest.scstatehouse.gov)', 0, H - 56, { align: 'center', width: W });

  // Gold accent bottom
  doc.rect(0, H - 6, W, 6).fill(GOLD);

  // =========================================================================
  // SCREENSHOT PAGES
  // =========================================================================
  for (let i = 0; i < APPS.length; i++) {
    const app = APPS[i];
    const imgFile = path.join(SCREENSHOTS_DIR, `${app.dir}.png`);

    if (!fs.existsSync(imgFile)) {
      console.log(`  SKIP ${app.dir} - screenshot not found`);
      continue;
    }

    doc.addPage({ layout: 'landscape', size: 'letter', margins: { top: 0, bottom: 0, left: 0, right: 0 } });

    // White background
    doc.rect(0, 0, W, H).fill(WHITE);
    // Top accent
    doc.rect(0, 0, W, 4).fill(NAVY);

    // Screenshot area
    const imgX = 40;
    const imgY = 24;
    const imgW = W - 80;
    const imgH = H - 80; // leave room for caption at bottom

    const imgBuffer = fs.readFileSync(imgFile);
    doc.image(imgBuffer, imgX, imgY, {
      fit: [imgW, imgH],
      align: 'center',
      valign: 'center',
    });

    // Border around image area
    doc.rect(imgX, imgY, imgW, imgH).lineWidth(0.5).strokeColor('#DDDDDD').stroke();

    // Caption at bottom
    const captionY = H - 48;

    doc.font('Helvetica-Bold').fontSize(16).fillColor(NAVY);
    const nameW = doc.widthOfString(app.name);
    drawText(doc, app.name, 50, captionY);

    doc.font('Helvetica').fontSize(14).fillColor(GOLD);
    const sep = '  \u2014  ';
    const sepW = doc.widthOfString(sep);
    drawText(doc, sep, 50 + nameW, captionY + 1);

    doc.fillColor(GRAY);
    drawText(doc, app.tagline, 50 + nameW + sepW, captionY + 1);

    // Bottom accent
    doc.rect(0, H - 4, W, 4).fill(NAVY);

    console.log(`  [${i + 1}/${APPS.length}] ${app.dir} - ${app.tagline}`);
  }

  // Remove any extra blank pages that pdfkit may have auto-created
  const pageRange = doc.bufferedPageRange();
  const expectedPages = 1 + APPS.length; // cover + screenshots
  if (pageRange.count > expectedPages) {
    console.log(`  Removing ${pageRange.count - expectedPages} extra blank page(s)`);
    // pdfkit doesn't support removing pages directly, but bufferPages +
    // switching to each valid page before end ensures only those are written
  }

  // Explicitly flip through only the pages we want
  for (let p = 0; p < Math.min(pageRange.count, expectedPages); p++) {
    doc.switchToPage(p);
  }

  doc.end();

  stream.on('finish', () => {
    const size = (fs.statSync(OUTPUT_PDF).size / 1024 / 1024).toFixed(1);
    console.log(`\nPDF created: ${OUTPUT_PDF} (${size} MB, ${expectedPages} pages)`);
  });
}

createPDF();
